# Funding platforms for groundlens.
# Reference: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
thanks_dev: gh/groundlens-dev
