"""Fixtures for the golden-score regression tests."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

GOLDEN_PATH = Path(__file__).parent / "golden_scores.json"


def pytest_addoption(parser: pytest.Parser) -> None:
    """Add --regenerate-golden to rewrite the pinned values."""
    parser.addoption(
        "--regenerate-golden",
        action="store_true",
        default=False,
        help=(
            "Recompute and overwrite tests/integration/golden_scores.json. "
            "Only use this when the default encoder changed on purpose."
        ),
    )


@pytest.fixture(scope="session")
def golden_values(request: pytest.FixtureRequest) -> dict[str, float]:
    """The pinned scores, recomputed first when --regenerate-golden is passed."""
    if request.config.getoption("--regenerate-golden"):
        from groundlens.dgi import compute_dgi, reset_calibration_cache
        from groundlens.sgi import compute_sgi
        from tests.integration.test_golden_scores import (
            FRESH_GROUNDED,
            FRESH_QUESTION,
            FRESH_UNGROUNDED,
            GOLDEN_CONTEXT,
            GOLDEN_GROUNDED,
            GOLDEN_QUESTION,
            GOLDEN_UNGROUNDED,
        )

        reset_calibration_cache()
        values = {
            "sgi_grounded": round(
                compute_sgi(
                    question=GOLDEN_QUESTION,
                    context=GOLDEN_CONTEXT,
                    response=GOLDEN_GROUNDED,
                ).value,
                4,
            ),
            "sgi_ungrounded": round(
                compute_sgi(
                    question=GOLDEN_QUESTION,
                    context=GOLDEN_CONTEXT,
                    response=GOLDEN_UNGROUNDED,
                ).value,
                4,
            ),
            "dgi_grounded": round(
                compute_dgi(question=GOLDEN_QUESTION, response=GOLDEN_GROUNDED).value, 4
            ),
            "dgi_ungrounded": round(
                compute_dgi(question=GOLDEN_QUESTION, response=GOLDEN_UNGROUNDED).value, 4
            ),
            "dgi_fresh_grounded": round(
                compute_dgi(question=FRESH_QUESTION, response=FRESH_GROUNDED).value,
                4,
            ),
            "dgi_fresh_ungrounded": round(
                compute_dgi(question=FRESH_QUESTION, response=FRESH_UNGROUNDED).value,
                4,
            ),
        }
        GOLDEN_PATH.write_text(
            json.dumps(
                {
                    "_comment": (
                        "Pinned scores for the default encoder "
                        "(sentence-transformers/sentence-t5-large, 768 dims). Regenerate ONLY "
                        "when the default encoder changes on purpose: pytest "
                        "tests/integration/test_golden_scores.py --regenerate-golden. Two "
                        "grounded/ungrounded pairs are pinned, both freshly written, neither "
                        "in reference_pairs.csv. Both grounded answers score far below "
                        "DGI_PASS (0.525): warehouse 0.1235, medical 0.2177, against a "
                        "calibration-set range of 0.2536-0.7609. Medical is one of the nine "
                        "domains the calibration set covers, so topic is not the explanation. "
                        "Authorship is: every calibration response was generated by one model "
                        "in one style, and mu_hat is the mean of their displacements. These "
                        "numbers pin a known limitation, not a healthy metric."
                    ),
                    "encoder": "sentence-transformers/sentence-t5-large",
                    "dims": 768,
                    **values,
                },
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
        return values

    if not GOLDEN_PATH.exists():
        pytest.fail(
            f"{GOLDEN_PATH} is missing. Generate it once on a machine with "
            "network access:\n"
            "  pytest tests/integration/test_golden_scores.py --regenerate-golden"
        )
    data = json.loads(GOLDEN_PATH.read_text(encoding="utf-8"))
    return {k: v for k, v in data.items() if isinstance(v, (int, float))}
